package view;

import javax.swing.JButton;
import javax.swing.JTable;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */

/**
 *
 * @author Marcus
 */
public class ClientesView extends javax.swing.JFrame implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer NewCustomizer
     */
    public ClientesView() {
        initComponents();
    }

    public JButton getBtnExcluir() {
        return btnExcluir;
    }

    public void setBtnExcluir(JButton btnExcluir) {
        this.btnExcluir = btnExcluir;
    }

    public JButton getBtnFecharComanda() {
        return btnFecharComanda;
    }

    public void setBtnFecharComanda(JButton btnFecharComanda) {
        this.btnFecharComanda = btnFecharComanda;
    }

    public JButton getBtnPedido() {
        return btnPedido;
    }

    public void setBtnPedido(JButton btnPedido) {
        this.btnPedido = btnPedido;
    }

    public JTable getTblNomes() {
        return tblNomes;
    }

    public void setTblNomes(JTable tblNomes) {
        this.tblNomes = tblNomes;
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPedido = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnFecharComanda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNomes = new javax.swing.JTable();

        btnPedido.setText("Pedido");
        jPanel1.add(btnPedido);

        btnExcluir.setText("Excluir");
        jPanel1.add(btnExcluir);

        btnFecharComanda.setText("Fechar Conta");
        jPanel1.add(btnFecharComanda);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        tblNomes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nome"
            }
        ));
        jScrollPane1.setViewportView(tblNomes);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFecharComanda;
    private javax.swing.JButton btnPedido;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNomes;
    // End of variables declaration//GEN-END:variables
}
